#!/bin/bash

echo "=== Git Authentication Setup ==="
echo ""
echo "Your commits are safely stored locally. To push to GitHub, you need to authenticate."
echo ""
echo "Option 1: Personal Access Token (Recommended)"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token (classic)'"
echo "3. Select scope: 'repo' (Full control of private repositories)"
echo "4. Copy the generated token"
echo "5. Run: git push origin dev-branch"
echo "6. Enter username: paccoco"
echo "7. Enter password: [paste your token]"
echo ""
echo "Option 2: Configure token in URL (one-time setup)"
echo "git remote set-url origin https://YOUR_TOKEN@github.com/Paccoco/MoP-Inscription-Deck-Tracker.git"
echo ""
echo "Option 3: SSH Keys"
echo "1. Generate SSH key: ssh-keygen -t ed25519 -C 'paccoco@users.noreply.github.com'"
echo "2. Add to GitHub: cat ~/.ssh/id_ed25519.pub"
echo "3. Change remote: git remote set-url origin git@github.com:Paccoco/MoP-Inscription-Deck-Tracker.git"
echo ""
echo "Current git status:"
git log --oneline -3
echo ""
echo "Ready to push: $(git rev-list origin/dev-branch..HEAD | wc -l) commits ahead"
